# Generated by Django 3.0.4 on 2020-03-14 23:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.TextField()),
                ('candidate_ref', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{8}$', message='Reference is invalid')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message="Score can't be less than 0.0"), django.core.validators.MaxValueValidator(100.0, message="Score can't be more than 100.0")])),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates_scores.Candidate')),
            ],
            options={
                'ordering': ('score',),
            },
        ),
    ]
